### ISSUE TITLE
Lush Jungle？

### ISSUE THREAD

**Issue by dante900210** [WrobotGames/Jungle-Demo-Setup#2]
![juNgle](https://github.com/user-attachments/assets/cc11c8dc-5659-44a4-91fc-eab9cb9b09df)

Why is it different from the one in the picture? I want this demo in the picture.

**Comment by WrobotGames** [comment]
Hi, this version on Github doesn't contain any of the copyrighted assets. You can download the full demo (no source code) on wrobot.itch.io

**Comment by WrobotGames** [comment]
Hi, this version on Github doesn't contain any of the copyrighted assets. You can download the full demo (no source code) on https://wrobot.itch.io

**Comment by dante900210** [comment]
So that's it. OK. Thank you！
